// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjcvdeufyybbpthzalkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqY3ZkZXVmeXliYnB0aHphbGt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyNzQ3MDYsImV4cCI6MjA2NDg1MDcwNn0.UKjZg7hasjDRtd4TFzcdzbppYNqKDjA9RejJ353aAMM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});